export const APP_CONFIG = {
    JWT_EXPIRY: '7d',
    REFRESH_TOKEN_EXPIRY: '30d',
    OTP_EXPIRY_MINUTE: 5,
    OTP_MAX_ATTEMPTS: 3,
    PASSWORD_SALT_ROUNDS: 10,
    MAX_FILES: 5 * 1024 * 1024,
    PAGINATION_DEFAULT_LIMIT: 20,
    PAGINATION_MAX_LIMIT: 100,
}

export const EWAY_BILL_MIN_INVOICE_AMOUNT = 50000;

export const INDIAN_STATES = [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    'Andaman and Nicobar Islands',
    'Chandigarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Jammu and Kashmir',
    'Ladakh',
    'Lakshadweep',
    'Puducherry',
] as const;


export const STATE_CODES: Record<string, string> = {
    'Andhra Pradesh': '37',
    'Arunachal Pradesh': '12',
    'Assam': '18',
    'Bihar': '10',
    'Chhattisgarh': '22',
    'Goa': '30',
    'Gujarat': '24',
    'Haryana': '06',
    'Himachal Pradesh': '02',
    'Jharkhand': '20',
    'Karnataka': '29',
    'Kerala': '32',
    'Madhya Pradesh': '23',
    'Maharashtra': '27',
    'Manipur': '14',
    'Meghalaya': '17',
    'Mizoram': '15',
    'Nagaland': '13',
    'Odisha': '21',
    'Punjab': '03',
    'Rajasthan': '08',
    'Sikkim': '11',
    'Tamil Nadu': '33',
    'Telangana': '36',
    'Tripura': '16',
    'Uttar Pradesh': '09',
    'Uttarakhand': '05',
    'West Bengal': '19',
    'Andaman and Nicobar Islands': '35',
    'Chandigarh': '04',
    'Dadra and Nagar Haveli and Daman and Diu': '26',
    'Delhi': '07',
    'Jammu and Kashmir': '01',
    'Ladakh': '38',
    'Lakshadweep': '31',
    'Puducherry': '34',
};

export const UNITS = [
    'PCS',
    'MTR',
    'KG',
    'GM',
    'LTR',
    'ML',
    'BOX',
    'PAIR',
    'SET',
    'DOZEN',
    'BUNDLE',
] as const;

export const ERROR_MESSAGES = {
    UNAUTHORIZED: 'Unauthorized access',
    FORBIDDEN: 'Access forbidden',
    NOT_FOUND: 'Resource not found',
    VALIDATION_ERROR: 'Validation failed',
    INTERNAL_ERROR: 'Internal server error',
    OTP_EXPIRED: 'OTP has expired',
    OTP_INVALID: 'Invalid OTP',
    OTP_MAX_ATTEMPTS: 'Maximum OTP attempts exceeded',
    DUPLICATE_ENTRY: 'Duplicate entry found',
    INSUFFICIENT_PERMISSIONS: 'Insufficient permissions',
    ORGANIZATION_NOT_FOUND: 'Organization not found',
    USER_NOT_FOUND: 'User not found',
    PARTY_NOT_FOUND: 'Party not found',
    PRODUCT_NOT_FOUND: 'Product not found',
    INVOICE_NOT_FOUND: 'Invoice not found',
    PAYMENT_NOT_FOUND: 'Payment not found',
    SUBSCRIPTION_EXPIRED: 'Subscription has expired',
    TRIAL_EXPIRED: 'Trial period has expired',
    INVOICE_LIMIT_EXCEEDED: 'Invoice limit exceeded for your plan',
    GSTIN_INVALID: 'Invalid GSTIN format',
    PAN_INVALID: 'Invalid PAN format',
    PHONE_INVALID: 'Invalid phone number',
    EMAIL_INVALID: 'Invalid email address',
} as const;
export const SUCCESS_MESSAGES = {
    OTP_SENT: 'OTP sent successfully',
    LOGIN_SUCCESS: 'Login successful',
    LOGOUT_SUCCESS: 'Logout successful',
    CREATED: 'Created successfully',
    UPDATED: 'Updated successfully',
    DELETED: 'Deleted successfully',
    PAYMENT_RECORDED: 'Payment recorded successfully',
    INVOICE_GENERATED: 'Invoice generated successfully',
    SYNC_COMPLETE: 'Sync completed successfully',
} as const;

